#!/usr/bin/env bash

# Only one instance of this script is guaranteed to run.
function run {
  if ! pgrep -f $1 ;
  then
    $@&
  fi
}

# Add desired autorun startup programs with arguments.

# Use slock as X lock screen for XScreenSaver if xss-lock and slock are on $PATH.
which xss-lock && which slock && run xss-lock slock
